/*

 LOGO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\ziqia\Downloads\GD-Demakes\GBDASH\software\logo.gbr
   Plane count   : 0.5 plane (4 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define logoWidth 20
#define logoHeight 18
#define logoBank 0

extern unsigned char logo[];

/* End of LOGO.H */
