/*

 MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 16
   Tile set      : C:\Users\Toshiba\Documents\GB\GBDash\software\tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapLabelWidth 64
#define MapLabelHeight 16
#define MapLabelBank 0

extern unsigned char MapLabel[];

/* End of MAP.H */
